# Generated by Django 5.0.4 on 2024-04-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_reg',
            old_name='user_contry',
            new_name='user_username',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='user_DOB',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='user_mob_number',
        ),
    ]
