# Generated by Django 5.0.4 on 2024-04-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0003_favourite_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_mon_yr',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
