# Generated by Django 5.0.4 on 2024-04-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0005_movies_agegroup_alter_movies_movie_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_genres',
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_duration',
            field=models.TextField(max_length=10),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starflixapp.genre'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=200)),
                ('episode_desc', models.TextField()),
                ('number', models.IntegerField()),
                ('TVshow_epi_mon_yr', models.TextField(max_length=30, null=True)),
                ('TVshow_epi_duration', models.TextField(max_length=10)),
                ('TVshow_file', models.FileField(upload_to='videos/')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='starflixapp.season')),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('show_desc', models.TextField()),
                ('movie_image', models.ImageField(upload_to='TVshow_image/')),
                ('movie_thumbnail', models.ImageField(upload_to='TVshow_thumbnail/')),
                ('imdb_rating', models.FloatField()),
                ('TVShow_mon_yr', models.TextField(max_length=30, null=True)),
                ('ageGroup', models.TextField(max_length=4, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('TVshow_trailer', models.FileField(upload_to='TVshow_Trailers/')),
                ('Tags', models.ManyToManyField(to='starflixapp.tags')),
                ('casts', models.ManyToManyField(to='starflixapp.cast')),
                ('crew', models.ManyToManyField(to='starflixapp.crew')),
                ('movie_genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starflixapp.genre')),
            ],
        ),
        migrations.AddField(
            model_name='season',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='starflixapp.tvshow'),
        ),
    ]
