# Generated by Django 5.0.4 on 2024-04-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0007_rename_movie_genre_tvshow_tvshow_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='TVShow_epi_image',
            field=models.ImageField(default='fortune_teller.jpg', upload_to='TVshow_epi_image/'),
        ),
    ]
