# Generated by Django 5.0.4 on 2024-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0009_rename_movie_genre_movies_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trendingORpriority',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='trendingORpriority',
            field=models.IntegerField(default=15),
        ),
    ]
