# Generated by Django 5.0.4 on 2024-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0011_tvshow_howmanyseasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='subscription',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
