# Generated by Django 5.0.4 on 2024-04-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0012_user_reg_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
