# Generated by Django 5.0.4 on 2024-04-30 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0013_movies_language_tvshow_language_alter_movies_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='starflixapp.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='starflixapp.tvshow'),
        ),
    ]
