# Generated by Django 5.0.4 on 2024-05-01 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0015_alter_movies_trendingorpriority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouritetv',
            old_name='tv_id',
            new_name='tvs_id',
        ),
        migrations.RenameField(
            model_name='watchlisttv',
            old_name='tv_id',
            new_name='tvs_id',
        ),
    ]
