# Generated by Django 5.0.4 on 2024-05-03 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0018_lastplayedmovie_lastplayedtv_delete_lastplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastplayedmovie',
            name='epi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starflixapp.episode'),
        ),
        migrations.DeleteModel(
            name='LastplayedTV',
        ),
    ]
