# Generated by Django 5.0.4 on 2024-05-03 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0019_lastplayedmovie_epi_id_delete_lastplayedtv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastplayedmovie',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starflixapp.movies'),
        ),
    ]
