# Generated by Django 5.0.4 on 2024-05-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0020_alter_lastplayedmovie_movie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastplayedmovie',
            name='epi_id',
        ),
        migrations.CreateModel(
            name='LastplayedTV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='starflixapp.episode')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starflixapp.user_reg')),
            ],
        ),
    ]
