# Generated by Django 5.0.4 on 2024-05-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0021_remove_lastplayedmovie_epi_id_lastplayedtv'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastplayedtv',
            name='minutes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lastplayedtv',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
