# Generated by Django 5.0.4 on 2024-05-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0022_lastplayedtv_minutes_watched_lastplayedtv_watched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastplayedmovie',
            name='minutes_watched',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lastplayedmovie',
            name='watched_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
