# Generated by Django 5.0.4 on 2024-05-04 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('starflixapp', '0023_lastplayedmovie_minutes_watched_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastplayedmovie',
            name='minutes_watched',
        ),
        migrations.RemoveField(
            model_name='lastplayedtv',
            name='minutes_watched',
        ),
    ]
